main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.Upload, name='upload'),
    path('update/<int:book_id>', views.update_book),
    path('delete/<int:book_id>', views.delete_book)
]

storecore/urls.py
from django.contrib import admin
from django.urls import path, include
from storecore.settings import DEBUG, STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

main/models.py
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=50)
    picture = models.ImageField()
    author = models.CharField(max_length=30, default='admin')
    email = models.EmailField(blank=True)
    describe = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Books'
        ordering = ('-created',)

    def __str__(self):
        return self.name

main/forms.py
import layout as layout
import picture as picture
from django import forms
from .models import Book
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, HTML, Field, Layout


class BookCreateForm(forms.ModelForm):
    name = forms.CharField(label='Ism', widget=forms.TextInput(attrs={'placeholder': 'Kitob nomi'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))

    class Meta:
        model = Book
        fields = ['name', 'picture', 'author', 'email', 'describe', 'price']
        labels = {
            'picture': "Rasm",
            'author': "Muallif",
            'email': "Email",
            'describe': "Tavsif",
            'price': "Narx",

        }

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.layout = Layout(
            HTML('')
        )
        for field in self.Meta().fields:
            helper.layout.append(
                Field(field, wrapper_class='row'),
            )
        helper.layout.append(Submit('submit', 'Submit', css_class='btn btn-primary'))
        helper.field_class = 'col-9'
        helper.label_class = 'col-2'
        return helper

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book
from .forms import BookCreateForm
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator


def index(request):
    shelf = Book.objects.order_by('-id')
    # Set UP paginator
    paginate = Paginator(Book.objects.all(), 4)
    page = request.GET.get('page')
    books = paginate.get_page(page)

    return render(request, 'main/index.html', {'shelf': shelf, 'books': books})


def Upload(request):
    upload = BookCreateForm()
    if request.method == 'POST':
        upload = BookCreateForm(request.POST, request.FILES)
        if upload.is_valid():
            upload.save()
            next_ = request.POST.get('next', '/')
            return HttpResponseRedirect(next_)
    else:
        return render(request, 'main/upload_form.html',
                      {'form': upload}
                      )


def update_book(request, book_id):
    username = get_object_or_404(Book, id=book_id)
    form = BookCreateForm(instance=username)
    if request.method == "POST":
        form = BookCreateForm(request.POST, request.FILES, instance=username)
        if form.is_valid():
            form.save()
            next_ = request.POST.get('next', '/')
            return HttpResponseRedirect(next_)

    return render(request, 'main/upload_form.html',
                  {'form': form}
                  )


def delete_book(request, book_id):
    book_id = int(book_id)
    try:
        book_sel = Book.objects.get(id=book_id)
    except Book.DoesNotExist:
        return redirect('main:index')
    book_sel.delete()
    return redirect('main:index')

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book Store</title>
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand bold fs-3" href="/">Book Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse fs-5" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item text-black">
                    <a class="nav-link btn btn-outline-success text-dark" href="{% url 'main:upload' %}"><i class="bi bi-upload me-2"></i>Upload</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}{% endblock %}
<script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>
</body>
</html>

templates/main/index.html
{% extends 'layouts/base.html' %}

{% block content %}

    <section class="">
        <div class="container py-5">
            <div class="row">
                {% for product in books %}
                    <div class="col col-lg-3">
                        <div class="card">
                            <img style="height: 400px;" class="card-img-top" alt="Responsive image"
                                 src="{{ product.picture.url }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.describe }}.</p>
                                <p class="card-text">{{ product.price }}</p>
                                <div class="d-flex justify-content-center">
                                    <a href="update/{{ product.id }}" class="btn btn-primary me-5"
                                       id='{{ product.id }}'><i class="bi bi-pencil-square me-1"></i>Edit</a>
                                    <a href="delete/{{ product.id }}" class="btn btn-danger ms-5"
                                       id='{{ product.id }}'><i class="bi bi-trash me-1"></i>Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <article>
            <div class="container pb-4">
                <nav aria-label="navigation">
                    <ul class="pagination justify-content-center">
                        {% if books.has_previous %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ books.previous_page_number }}">Previous</a>
                            </li>
                        {% endif %}
                        <li class="page-item"><a class="page-link" href="#">{{ books.number }}</a></li>
                        <li class="page-item"><a class="page-link" href="#">of</a></li>
                        <li class="page-item"><a class="page-link" href="#">{{ books.paginator.num_pages }}</a></li>
                        {% if books.has_next %}
                            <li class="page-item"><a class="page-link"
                                                     href="?page={{ books.next_page_number }}">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            </div>
        </article>
    </section>
{% endblock %}

templates/main/upload_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-4">
        <div class="d-flex justify-content-center">
            <div class="card shadow-sm rounded">
                <div class="card-header fw-bold text-center">
                    Upload Books
                </div>
                <div class="card-body">
                    <div class="card-text">
                        <form method='POST' enctype="multipart/form-data">
                            {% csrf_token %}
                            {% crispy form %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}